# Generated by Django 4.2.7 on 2023-12-22 20:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(default='', max_length=1000)),
                ('gid', models.CharField(default='', max_length=1000)),
                ('name', models.CharField(default='', max_length=1000)),
                ('state', models.CharField(default='', max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegionStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(default='', max_length=1000)),
                ('data', models.JSONField(default={})),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='home.region')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
