# Generated by Django 4.2.7 on 2024-01-08 01:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_savedmarket_gid_remove_savedmarket_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedMarketNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(default='', max_length=10000)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='home.savedmarket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
