# Generated by Django 4.2.7 on 2023-12-01 19:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last_login')),
                ('forced_password_reset', models.BooleanField(default=False)),
                ('password_reset_code', models.CharField(default=uuid.uuid4, max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
