# Generated by Django 4.2.7 on 2024-02-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_beta_user_lia_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_point_preferences',
            field=models.JSONField(default=['1mo STR', '3mo STR', '6mo STR', '1yr STR']),
        ),
    ]
